GCLOUD_LOCATION: "us-central1"
GCLOUD_PROJECT_ID: "fair-subset-473900-p4"
BACKEND_URL: "http://localhost:8081/chat"
STORAGE_BUCKET_NAME: "personal-expense-assistantttt"
DB_COLLECTION_NAME: "personal-expense-assistant-receipts"